### ISSUE TITLE
Error:  undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by petrsvihlik** [RadoslavK/jekyll-blog#3]
### `bundle exec jekyll build`
causes:

> Configuration file: C:/Users/petrs/Documents/GitHub/jekyll-blog/_config.yml
>        Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
>             Source: C:/Users/petrs/Documents/GitHub/jekyll-blog
>        Destination: C:/Users/petrs/Documents/GitHub/jekyll-blog/_site
>  Incremental build: disabled. Enable with --incremental
>       Generating...
> Importing from Kentico Cloud...
> jekyll 3.8.5 | Error:  undefined method `[]' for nil:NilClass
> PS C:\Users\petrs\Documents\GitHub\jekyll-blog> bundle exec jekyll build --trace
> Configuration file: C:/Users/petrs/Documents/GitHub/jekyll-blog/_config.yml
>        Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
>             Source: C:/Users/petrs/Documents/GitHub/jekyll-blog
>        Destination: C:/Users/petrs/Documents/GitHub/jekyll-blog/_site
>  Incremental build: disabled. Enable with --incremental
>       Generating...
> Importing from Kentico Cloud...
> Traceback (most recent call last):
>         29: from C:/Ruby26-x64/bin/jekyll:23:in `<main>'
>         28: from C:/Ruby26-x64/bin/jekyll:23:in `load'
>         27: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
>         26: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
>         25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
>         24: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
>         23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
>         22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
>         21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
>         20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:36:in `process'
>         19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:65:in `build'
>         18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/command.rb:28:in `process_site'
>         17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:70:in `process'
>         16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:173:in `generate'
>         15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:173:in `each'
>         14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:175:in `block in generate'
>         13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-kentico-0.8.0/lib/jekyll-kentico/generator.rb:20:in `generate'
>         12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-kentico-0.8.0/lib/jekyll-kentico/generator.rb:52:in `process_site'
>         11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-kentico-0.8.0/lib/jekyll-kentico/generator.rb:52:in `each'
>         10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-kentico-0.8.0/lib/jekyll-kentico/generator.rb:53:in `block in process_site'
>          9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-kentico-0.8.0/lib/jekyll-kentico/site_processing/kentico_cloud_importer.rb:38:in `pages'
>          8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-kentico-0.8.0/lib/jekyll-kentico/site_processing/kentico_cloud_importer.rb:176:in `generate_pages'
>          7: from C:/Ruby26-x64/lib/ruby/2.6.0/ostruct.rb:146:in `each_pair'
>          6: from C:/Ruby26-x64/lib/ruby/2.6.0/ostruct.rb:146:in `each_pair'
>          5: from C:/Ruby26-x64/lib/ruby/2.6.0/ostruct.rb:146:in `block in each_pair'
>          4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-kentico-0.8.0/lib/jekyll-kentico/site_processing/kentico_cloud_importer.rb:183:in `block in generate_pages'
>          3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-kentico-0.8.0/lib/jekyll-kentico/site_processing/kentico_cloud_importer.rb:183:in `each'
>          2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-kentico-0.8.0/lib/jekyll-kentico/site_processing/kentico_cloud_importer.rb:184:in `block (2 levels) in generate_pages'
>          1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-kentico-0.8.0/lib/jekyll-kentico/resolvers/content_resolver.rb:21:in `resolve'
> C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/delivery-sdk-ruby-1.0.4/lib/delivery/models/content_item.rb:65:in `get_string': undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by petrsvihlik** [comment]
`$ bundle update`
